Vagrant.configure("2") do |config|
  config.vm.synced_folder "./data", "/var/www/html"
  config.vm.box = "generic/ubuntu2204"
  config.vm.provision :shell, path: "final_provision.sh"
  config.vm.network "private_network", ip: "192.168.33.10"
end


